### ISSUE TITLE
DzDataMeshGovInfraStack faild deploy

### ISSUE THREAD

**Issue by yoshikikasama** [aws-samples/data-mesh-datazone-cdk-cloudformation#8]
Thank you for your appreciation of the implementation. However,  the deployment is still not succeeding. How can I make this work successfully?
Based on the error message, the main issue is that the DataZone environment creation is failing. Specifically, the process is unable to add the role “AmazonDataZoneGlueAccess-<role>” as a data lake administrator. The error states that an invalid principal was detected.
>   DzDataMeshGovInfraStack failed: The stack named DzDataMeshGovInfraStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: “Environment Admin-DataLakeEnvironment with id <id> and domain id <id> failed to stabilize due to internal failure, last deployment status Deployment(DeploymentId=<id>, DeploymentStatus=FAILED, DeploymentType=CREATE, FailureReason=EnvironmentError(Code=400, Message=Failed to add arn:aws:iam::<AWS_ACCOUNT_ID>:role/AmazonDataZoneGlueAccess-<region>-<ID> as data lake administrator: invalid principal detected. Please check if an invalid principal is configured as a data lake administrator in account <AWS_ACCOUNT_ID> and region <region>), IsDeploymentComplete=true)” (RequestToken: <token>, HandlerErrorCode: NotStabilized)

**Comment by marjet26** [comment]
Hello @yoshikikasama , 

Thank you for raising this issue! Could you please confirm that an invalid principal is not configured as a data lake administrator from the Lake Formation console?

**Comment by yoshikikasama** [comment]
Hello @marjet26 ,

Thank you for your response and guidance! I apologize for the oversight on my part. I checked the Lake Formation console as you suggested and found an invalid principal configured as a data lake administrator. After removing it, the deployment went through successfully.

Thank you for your support. It's a good reminder for me to always double-check these configurations in the future.
